affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
configProdJson:
  configmap:
    config.prod.json: |
      {
          "env": {
              "name": "qa",
              "impersonate": true,
              "impersonateUrl": ".deliverin.my"
          },
          "apiServer": {
              "flowBuilderService"  : "https://api.symplified.biz/flow-builder/v1",
              "userService"         : "https://api.symplified.biz/user-service/v1",
              "productService"      : "https://api.symplified.biz/product-service/v1",
              "orderService"        : "https://api.symplified.biz/order-service/v1",
              "reportService"       : "https://api.symplified.biz/report-service/v1",
              "deliveryService"     : "https://api.symplified.biz/delivery-service/v1",
              "paymentService"      : "https://api.symplified.biz/payment-service/v1",
              "analyticService"     : "https://api.symplified.biz/analytic-service/v1"
          },
          "storeFrontDomain"          : ".deliverin.my",
          "marketplaceDomain"         : "customer.deliverin.my",
          "merchantPortalDomain"      : "merchant.symplified.biz",
          "logging": 0
      }
  volumeMount:
  - mountPath: /usr/local/apache2/htdocs/assets/config/config.prod.json
    name: store-front-x-cpj-vol
    subPath: config.prod.json
  volumes:
  - configMap:
      name: store-front-x-cpj-cm
    name: store-front-x-cpj-vol
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: kalsym/store-front-x
  tag: 1.2.1
imagePullSecrets:
- name: kalsym-docker-hub
ingress:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location = / {
        if ($host = 'qa-my.symplified.ai') {
          set $temp_cache 1;
        }
        if ($request_uri !~ '\?') {
          set $temp_cache 1$temp_cache;
        }
        if ($temp_cache = 11) {
          return 302 https://symplified.it;
        }
      }
  className: ""
  enabled: true
  hosts:
  - host: qa-my.symplified.ai
    paths:
    - path: /
      pathType: Prefix
  - host: '*.qa-my.symplified.ai'
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - qa-my.symplified.ai
    - '*.qa-my.symplified.ai'
    secretName: secret-tls-ai
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 8080
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: false
  name: ""
tolerations: []